#CentOS/RedHat only
hadoop_repository_file_hdp: '/etc/yum.repos.d/hdp.repo'
hadoop_repository_file_ambari: '/etc/yum.repos.d/ambari.repo'
hadoop_repository_repo_url_hdp: 'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.0.6.1/hdp.repo'
hadoop_repository_repo_url_ambari: 'http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos6/2.x/latest/2.1.0/ambari.repo'
hadoop_repository_user: 'root'
hadoop_repository_group: 'root'
hadoop_repository_perm: 0644
